# Generated by Django 4.2.4 on 2023-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_type',
            field=models.CharField(blank=True, choices=[('Artist', 'Artist'), ('Promoter', 'Promoter'), ('PR Agent', 'PR Agent'), ('Label', 'Label'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_influence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
