# Generated by Django 4.2.4 on 2023-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_company_customuser_company_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='influencer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='music_styles',
            field=models.CharField(blank=True, choices=[('Techno', 'Techno'), ('EDM', 'EDM'), ('House', 'House'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
