# Generated by Django 4.2.4 on 2023-08-21 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='date_request',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CampaignResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_post_link', models.URLField()),
                ('reach', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField()),
                ('screenshots', models.FileField(upload_to='screenshoots/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
