# Generated by Django 4.2.4 on 2023-08-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_alter_promo_date_request_campaignresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='date_request',
            field=models.DateTimeField(),
        ),
    ]
